# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suadeo1.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 565)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(23, 27, 58);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(70, 30, 801, 31))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.filmsButton = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filmsButton.sizePolicy().hasHeightForWidth())
        self.filmsButton.setSizePolicy(sizePolicy)
        self.filmsButton.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color: rgb(78, 84, 140);\n"
"border: 1px solid rgb(78, 84, 140);\n"
"border-radius: 15px;\n"
"width: 130px;\n"
"height: 50px;\n"
"}\n"
"QPushButon:pressed {\n"
"background-color: rgb(149, 255, 223);\n"
"}")
        self.filmsButton.setObjectName("filmsButton")
        self.booksButton = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booksButton.sizePolicy().hasHeightForWidth())
        self.booksButton.setSizePolicy(sizePolicy)
        self.booksButton.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color: rgb(78, 84, 140);\n"
"border: 1px solid rgb(78, 84, 140);\n"
"border-radius: 15px;\n"
"width: 130px;\n"
"height: 50px;\n"
"}\n"
"QPushButon:pressed {\n"
"background-color: rgb(149, 255, 223);\n"
"}")
        self.booksButton.setObjectName("booksButton")
        self.musicButton = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.musicButton.sizePolicy().hasHeightForWidth())
        self.musicButton.setSizePolicy(sizePolicy)
        self.musicButton.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color: rgb(78, 84, 140);\n"
"border: 1px solid rgb(78, 84, 140);\n"
"border-radius: 15px;\n"
"width: 130px;\n"
"height: 50px;\n"
"}\n"
"QPushButon:pressed {\n"
"background-color: rgb(149, 255, 223);\n"
"}")
        self.musicButton.setObjectName("musicButton")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setGeometry(QtCore.QRect(70, 100, 801, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.searchBar = QtWidgets.QLineEdit(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBar.sizePolicy().hasHeightForWidth())
        self.searchBar.setSizePolicy(sizePolicy)
        self.searchBar.setStyleSheet("border: 1px solid rgb(92, 104, 213);\n"
"border-radius:20px;\n"
"background-color: rgb(92, 104, 213);")
        self.searchBar.setObjectName("searchBar")
        self.searchButton = QtWidgets.QPushButton(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMaximumSize(QtCore.QSize(120, 50))
        self.searchButton.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color: rgb(149, 255, 223);\n"
"border: 1px solid rgb(149, 255, 223);\n"
"border-radius: 20px;\n"
"width: 80px;\n"
"height: 50px;\n"
"}\n"
"")
        self.searchButton.setObjectName("searchButton")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(70, 207, 791, 121))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.result1 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result1.sizePolicy().hasHeightForWidth())
        self.result1.setSizePolicy(sizePolicy)
        self.result1.setStyleSheet("background-color: rgb(78, 84, 140);\n"
"border-radius: 15px;")
        self.result1.setObjectName("result1")
        self.result2 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result2.sizePolicy().hasHeightForWidth())
        self.result2.setSizePolicy(sizePolicy)
        self.result2.setStyleSheet("background-color: rgb(78, 84, 140);\n"
"border-radius: 15px;")
        self.result2.setObjectName("result2")
        self.result3 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result3.sizePolicy().hasHeightForWidth())
        self.result3.setSizePolicy(sizePolicy)
        self.result3.setStyleSheet("background-color: rgb(78, 84, 140);\n"
"border-radius: 15px;")
        self.result3.setObjectName("result3")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(140, 330, 711, 28))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setGeometry(QtCore.QRect(70, 360, 791, 121))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.result4 = QtWidgets.QLabel(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result4.sizePolicy().hasHeightForWidth())
        self.result4.setSizePolicy(sizePolicy)
        self.result4.setStyleSheet("background-color: rgb(78, 84, 140);\n"
"border-radius: 15px;")
        self.result4.setObjectName("result4")
        self.result5 = QtWidgets.QLabel(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result5.sizePolicy().hasHeightForWidth())
        self.result5.setSizePolicy(sizePolicy)
        self.result5.setStyleSheet("background-color: rgb(78, 84, 140);\n"
"border-radius: 15px;")
        self.result5.setObjectName("result5")
        self.result6 = QtWidgets.QLabel(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result6.sizePolicy().hasHeightForWidth())
        self.result6.setSizePolicy(sizePolicy)
        self.result6.setStyleSheet("background-color: rgb(78, 84, 140);\n"
"border-radius: 15px;")
        self.result6.setObjectName("result6")
        self.splitter_7 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_7.setGeometry(QtCore.QRect(60, 480, 821, 58))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filmsButton.setText(_translate("MainWindow", "Films"))
        self.booksButton.setText(_translate("MainWindow", "Books"))
        self.musicButton.setText(_translate("MainWindow", "Music"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.result1.setText(_translate("MainWindow", "TextLabel"))
        self.result2.setText(_translate("MainWindow", "TextLabel"))
        self.result3.setText(_translate("MainWindow", "TextLabel"))
        self.result4.setText(_translate("MainWindow", "TextLabel"))
        self.result5.setText(_translate("MainWindow", "TextLabel"))
        self.result6.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
